# Generated by Django 5.0.2 on 2024-03-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('size', models.FloatField(null=True)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_download_datetime', models.DateTimeField(null=True)),
                ('unique_name', models.CharField(max_length=100, null=True, unique=True)),
                ('url_storage', models.URLField(null=True, unique=True)),
                ('url_download', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
